version: "2.1"

services:
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
